// Representative subset of DMC 6-strand embroidery floss colours
// code → DMC floss number | name → thread name | hex → closest web colour
const DMC_COLORS = [
  // ── Whites & Neutrals ──────────────────────────────────────────────────────
  { code: 'B5200', name: 'Snow White',               hex: '#FFFFFF' },
  { code: 'blanc', name: 'White',                    hex: '#F8F8F8' },
  { code: 'ecru',  name: 'Ecru',                     hex: '#F5EDCA' },
  { code: '3865',  name: 'Winter White',             hex: '#F4F0E8' },
  { code: '3024',  name: 'Very Light Brown Gray',    hex: '#D4C8B4' },
  { code: '3023',  name: 'Brown Gray Light',         hex: '#B4A890' },
  { code: '3022',  name: 'Brown Gray Medium',        hex: '#8C7D6E' },
  { code: '762',   name: 'Pearl Gray Very Light',    hex: '#E8E8E8' },
  { code: '415',   name: 'Pearl Gray',               hex: '#C8C8C8' },
  { code: '318',   name: 'Steel Gray Light',         hex: '#A0A0A0' },
  { code: '414',   name: 'Steel Gray Dark',          hex: '#787878' },
  { code: '317',   name: 'Pewter Gray',              hex: '#646464' },
  { code: '413',   name: 'Pewter Gray Dark',         hex: '#505050' },
  { code: '535',   name: 'Ash Gray Very Light',      hex: '#8C8C8C' },
  { code: '3799',  name: 'Very Dark Pewter',         hex: '#3C3C3C' },
  { code: '310',   name: 'Black',                    hex: '#1A1A1A' },

  // ── Reds ───────────────────────────────────────────────────────────────────
  { code: '666',   name: 'Bright Red',               hex: '#E0001E' },
  { code: '321',   name: 'Red',                      hex: '#B50014' },
  { code: '498',   name: 'Christmas Red Dark',       hex: '#82001E' },
  { code: '816',   name: 'Garnet',                   hex: '#780014' },
  { code: '815',   name: 'Garnet Medium',            hex: '#640014' },
  { code: '817',   name: 'Coral Red Very Dark',      hex: '#CC1414' },
  { code: '3801',  name: 'Very Dark Christmas Red',  hex: '#CC0028' },
  { code: '347',   name: 'Salmon Very Dark',         hex: '#961432' },

  // ── Pinks & Roses ──────────────────────────────────────────────────────────
  { code: '151',   name: 'Dusty Rose Very Light',    hex: '#F5C8C8' },
  { code: '152',   name: 'Shell Pink Medium Light',  hex: '#E09696' },
  { code: '3713',  name: 'Salmon Very Light',        hex: '#FFD8CC' },
  { code: '760',   name: 'Salmon',                   hex: '#F5A090' },
  { code: '761',   name: 'Salmon Light',             hex: '#FFC8B4' },
  { code: '3712',  name: 'Salmon Medium',            hex: '#E58070' },
  { code: '957',   name: 'Pale Geranium',            hex: '#FFB4B9' },
  { code: '956',   name: 'Geranium',                 hex: '#FF8C8C' },
  { code: '3608',  name: 'Plum Very Light',          hex: '#F0A0D2' },
  { code: '3607',  name: 'Plum Light',               hex: '#D264B4' },
  { code: '3350',  name: 'Dusty Rose Ultra Dark',    hex: '#A03C5A' },
  { code: '3688',  name: 'Mauve Medium Light',       hex: '#D28CA0' },
  { code: '3687',  name: 'Mauve',                    hex: '#C06478' },

  // ── Oranges & Corals ──────────────────────────────────────────────────────
  { code: '352',   name: 'Coral Light',              hex: '#FF9680' },
  { code: '351',   name: 'Coral',                    hex: '#E87860' },
  { code: '350',   name: 'Coral Medium',             hex: '#D05040' },
  { code: '349',   name: 'Coral Dark',               hex: '#B03C2C' },
  { code: '947',   name: 'Burnt Orange',             hex: '#FF5C14' },
  { code: '946',   name: 'Burnt Orange Medium',      hex: '#E84B00' },
  { code: '900',   name: 'Burnt Orange Dark',        hex: '#C83200' },
  { code: '919',   name: 'Red Copper',               hex: '#BE4A00' },
  { code: '918',   name: 'Red Copper Dark',          hex: '#882800' },

  // ── Yellows & Golds ───────────────────────────────────────────────────────
  { code: '3823',  name: 'Yellow Ultra Pale',        hex: '#FFFCE4' },
  { code: '3078',  name: 'Golden Yellow Very Light', hex: '#FFF5C8' },
  { code: '727',   name: 'Topaz Very Light',         hex: '#FFEE99' },
  { code: '726',   name: 'Topaz Light',              hex: '#FFDC50' },
  { code: '725',   name: 'Topaz Medium Light',       hex: '#FFC83C' },
  { code: '783',   name: 'Medium Topaz',             hex: '#CF8C14' },
  { code: '782',   name: 'Medium Dark Topaz',        hex: '#AA6408' },
  { code: '781',   name: 'Very Dark Topaz',          hex: '#875014' },
  { code: '780',   name: 'Ultra Dark Topaz',         hex: '#6E3C0A' },
  { code: '744',   name: 'Yellow Pale',              hex: '#FFEE6E' },
  { code: '743',   name: 'Yellow Medium',            hex: '#FFCC14' },
  { code: '742',   name: 'Tangerine Light',          hex: '#FFAA00' },
  { code: '741',   name: 'Tangerine Medium',         hex: '#FF8C00' },
  { code: '740',   name: 'Tangerine',                hex: '#FF6400' },
  { code: '834',   name: 'Golden Olive Very Light',  hex: '#D4A832' },
  { code: '833',   name: 'Golden Olive Light',       hex: '#BE9028' },
  { code: '832',   name: 'Golden Olive Medium',      hex: '#A07820' },

  // ── Greens ────────────────────────────────────────────────────────────────
  { code: '907',   name: 'Parrot Green Light',       hex: '#96D200' },
  { code: '906',   name: 'Parrot Green Medium',      hex: '#7DB400' },
  { code: '905',   name: 'Parrot Green Dark',        hex: '#629100' },
  { code: '904',   name: 'Parrot Green Very Dark',   hex: '#4D7200' },
  { code: '3819',  name: 'Moss Green Light',         hex: '#C8D246' },
  { code: '3817',  name: 'Celadon Green Light',      hex: '#9EC8B4' },
  { code: '3816',  name: 'Celadon Green',            hex: '#6DAF96' },
  { code: '3815',  name: 'Celadon Green Dark',       hex: '#4A8C7D' },
  { code: '955',   name: 'Nile Green Light',         hex: '#AADCAA' },
  { code: '954',   name: 'Nile Green',               hex: '#72C872' },
  { code: '913',   name: 'Medium Nile Green',        hex: '#50A850' },
  { code: '912',   name: 'Emerald Green Light',      hex: '#2D9050' },
  { code: '911',   name: 'Emerald Green Medium',     hex: '#1E7832' },
  { code: '910',   name: 'Emerald Green Dark',       hex: '#0F6028' },
  { code: '909',   name: 'Emerald Green Very Dark',  hex: '#005A1E' },
  { code: '368',   name: 'Pistachio Green Light',    hex: '#A0C890' },
  { code: '320',   name: 'Pistachio Green Medium',   hex: '#6FA070' },
  { code: '367',   name: 'Pistachio Green Dark',     hex: '#507A50' },
  { code: '319',   name: 'Pistachio Green Very Dark',hex: '#3A6E3A' },
  { code: '501',   name: 'Blue Green Dark',          hex: '#2D5A41' },
  { code: '502',   name: 'Blue Green',               hex: '#647D69' },
  { code: '503',   name: 'Blue Green Medium',        hex: '#8CAA8C' },
  { code: '504',   name: 'Blue Green Very Light',    hex: '#B4CDB9' },
  { code: '164',   name: 'Forest Green Light',       hex: '#82A082' },
  { code: '163',   name: 'Celadon Green Medium',     hex: '#4E8264' },
  { code: '3818',  name: 'Emerald Green Ultra Dark', hex: '#004632' },

  // ── Blues ─────────────────────────────────────────────────────────────────
  { code: '828',   name: 'Baby Blue Ultra Very Light', hex: '#D8EEFF' },
  { code: '827',   name: 'Blue Very Light',           hex: '#BDD8EE' },
  { code: '3325',  name: 'Baby Blue Light',           hex: '#A8CDE8' },
  { code: '3755',  name: 'Baby Blue',                 hex: '#6EA0C3' },
  { code: '826',   name: 'Blue Medium',               hex: '#4878A0' },
  { code: '825',   name: 'Blue Dark',                 hex: '#285A82' },
  { code: '824',   name: 'Blue Very Dark',            hex: '#1E4669' },
  { code: '336',   name: 'Navy Blue',                 hex: '#0F2850' },
  { code: '312',   name: 'Baby Blue Very Dark',       hex: '#1E3C64' },
  { code: '322',   name: 'Baby Blue Dark',            hex: '#3A6496' },
  { code: '820',   name: 'Royal Blue Very Dark',      hex: '#1A3282' },
  { code: '3840',  name: 'Lavender Blue Light',       hex: '#A0B4E6' },
  { code: '3839',  name: 'Lavender Blue Medium',      hex: '#7896CC' },
  { code: '3838',  name: 'Lavender Blue Dark',        hex: '#5A7AB4' },
  { code: '518',   name: 'Wedgwood Light',            hex: '#4B8CB4' },
  { code: '517',   name: 'Wedgwood Dark',             hex: '#285A82' },
  { code: '519',   name: 'Sky Blue',                  hex: '#78B4D2' },
  { code: '807',   name: 'Peacock Blue',              hex: '#4BA8BE' },
  { code: '806',   name: 'Peacock Blue Dark',         hex: '#2882A0' },
  { code: '3848',  name: 'Teal Green Medium',         hex: '#3A8C96' },
  { code: '3849',  name: 'Teal Green Light',          hex: '#5EB4BE' },
  { code: '3814',  name: 'Aquamarine',                hex: '#28826E' },

  // ── Purples & Violets ─────────────────────────────────────────────────────
  { code: '211',   name: 'Lavender Light',            hex: '#D2B4D2' },
  { code: '210',   name: 'Lavender Medium',           hex: '#B478B4' },
  { code: '209',   name: 'Lavender Dark',             hex: '#8C508C' },
  { code: '208',   name: 'Lavender Very Dark',        hex: '#6E3282' },
  { code: '550',   name: 'Violet Very Dark',          hex: '#46006E' },
  { code: '552',   name: 'Violet Medium',             hex: '#7828A0' },
  { code: '553',   name: 'Violet',                    hex: '#8C4BA0' },
  { code: '554',   name: 'Violet Light',              hex: '#B478BF' },
  { code: '327',   name: 'Violet Dark',               hex: '#5F1E82' },
  { code: '333',   name: 'Blue Violet Very Dark',     hex: '#3C3C78' },
  { code: '340',   name: 'Blue Violet Medium',        hex: '#8278B4' },
  { code: '341',   name: 'Blue Violet Light',         hex: '#A8A0CC' },
  { code: '718',   name: 'Plum',                      hex: '#96287D' },
  { code: '917',   name: 'Plum Medium',               hex: '#B41478' },
  { code: '915',   name: 'Plum Dark',                 hex: '#820064' },

  // ── Browns ────────────────────────────────────────────────────────────────
  { code: '739',   name: 'Tan Ultra Very Light',      hex: '#F5E4C8' },
  { code: '738',   name: 'Tan Very Light',            hex: '#F0D2A0' },
  { code: '437',   name: 'Tan Light',                 hex: '#D4A064' },
  { code: '436',   name: 'Tan',                       hex: '#C07832' },
  { code: '435',   name: 'Brown Very Light',          hex: '#AA6428' },
  { code: '434',   name: 'Brown Light',               hex: '#B46428' },
  { code: '433',   name: 'Brown Medium',              hex: '#8C4B14' },
  { code: '801',   name: 'Coffee Brown Dark',         hex: '#5A2D08' },
  { code: '842',   name: 'Beige Brown Very Light',    hex: '#D4B490' },
  { code: '841',   name: 'Beige Brown Light',         hex: '#B48C69' },
  { code: '840',   name: 'Beige Brown Medium',        hex: '#8C6441' },
  { code: '839',   name: 'Beige Brown Dark',          hex: '#6E4828' },
  { code: '838',   name: 'Beige Brown Very Dark',     hex: '#4B3220' },
  { code: '3033',  name: 'Mocha Brown Very Light',    hex: '#D4C8B4' },
  { code: '3032',  name: 'Mocha Brown Medium',        hex: '#8C7050' },
];

module.exports = DMC_COLORS;
